apiVersion: apps/v1
kind: Deployment
metadata:
  name: tailspin-space-web
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: tailspinspace
  template:
    metadata:
      labels:
        app: tailspinspace
    spec:
      containers:
      - name: tailspinspace
        image: darquewarrior.azurecr.io/tailspinspacegameweb:${{ github.run_number }}
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: tailspinspace
  labels:
    app: tailspinspace
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: tailspinspace
